### ISSUE TITLE
下载时，出现如下错误

### ISSUE THREAD

**Issue by HelloWorDomain** [Prince-cool/tx_course_download#11]
下载时，出现如下错误：
时间：2022年10月6日
Traceback (most recent call last):
  File "download.py", line 226, in <module>
    realurl,key=get_realurl(term_id,resid_list)
  File "download.py", line 98, in get_realurl
    key=ctx.call('get_key',d_sign)
  File "execjs\_abstract_runtime_context.py", line 37, in call
  File "execjs\_external_runtime.py", line 92, in _call
  File "execjs\_external_runtime.py", line 78, in _eval
  File "execjs\_abstract_runtime_context.py", line 18, in exec_
  File "execjs\_external_runtime.py", line 88, in _exec_
  File "execjs\_external_runtime.py", line 167, in _extract_result
execjs._exceptions.ProgramError: TypeError: 'global' 未定义
[18644] Failed to execute script 'download' due to unhandled exception!

**Comment by Prince-cool** [comment]
先安装nodejs环境

**Comment by HelloWorDomain** [comment]
谢谢
安装node-v16.17.1-x64.msi
后，已经可以正常运行。

**Comment by HelloWorDomain** [comment]
是我没有好好读README中的这一段。
新版本先安装好node环境！！！
