### ISSUE TITLE
下载报错，用的新版

### ISSUE THREAD

**Issue by lztymc** [Prince-cool/tx_course_download#8]
请输入你的课程编号:11
-------
Web自动化项目实战：自动化测试理论
Traceback (most recent call last):
  File "download.py", line 167, in <module>
    realurl,key=get_realurl(term_id,resid_list)
  File "download.py", line 98, in get_realurl
    key=ctx.call('get_key',d_sign)
  File "execjs\_abstract_runtime_context.py", line 37, in call
  File "execjs\_external_runtime.py", line 92, in _call
  File "execjs\_external_runtime.py", line 78, in _eval
  File "execjs\_abstract_runtime_context.py", line 18, in exec_
  File "execjs\_external_runtime.py", line 88, in _exec_
  File "execjs\_external_runtime.py", line 167, in _extract_result
execjs._exceptions.ProgramError: TypeError: 'global' 未定义
[16460] Failed to execute script 'download' due to unhandled exception!

C:\shiyong\tx课堂下载器 v3.0>

**Comment by Prince-cool** [comment]
请安装nodejs环境
